version: '3.4'

services:
  app:
    environment:
      ENV: localdev
      PORT: 8000
      AUTH: BLTI_DEV
      LTI_DEVELOP_APP: rttlinfo
    restart: always
    container_name: app-rttlinfo
    build:
      context: .
      target: app-container
    volumes:
      - ./rttlinfo:/app/rttlinfo
    ports:
      - "8000:8000"
