ingress:
  enabled: true
  tls:
   rttlinfo:
      secretName: test-rttlinfo.canvas.uw.edu-ingress-cert
      hosts:
        - test-rttlinfo.canvas.uw.edu
  hosts:
   rttlinfo:
      host: test-rttlinfo.canvas.uw.edu
      paths:
        - "/"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
lifecycle:
  enabled: true
  preStop:
    enabled: true
affinity:
   podsSpanNodes: true
readiness:
  enabled: true
securityPolicy:
  enabled: true
database:
  engine: null
repo: rttl-info-lti
instance: test
memcached:
  enabled: true
  replicaCount: 1
  updateStrategy:
    type: RollingUpdate
certs:
  mounted: true
  certPath: /certs/rttlinfo.canvas.uw.edu-ic.cert
  keyPath: /certs/rttlinfo.canvas.uw.edu-ic.key
  secretName: test-rttlinfo.canvas.uw.edu-ic-certs
environmentVariables:
  - name: CLUSTER_CNAME
    value: test-rttlinfo.canvas.uw.edu
  - name: AUTH
    value: BLTI
  - name: ENV
    value: test
  - name: SESSION_BACKEND
    value: MEMCACHED
  - name: PWS_ENV
    value: PROD
  - name: CANVAS_ENV
    value: EVAL
  - name: CANVAS_TIMEOUT
    value: "10"
externalSecrets:
  enabled: true
  secrets:
    - name: test-rttlinfo.canvas.uw.edu-secrets
      externalKey: rttl-info-lti/test/secrets
      data:
        - name: django-secret
          property: django-secret
    - name: test-rttlinfo.canvas.uw.edu-shared-secrets
      externalKey: rttl-info-lti/shared/secrets
      data:
        - name: lti-consumers
          property: lti-consumers
        - name: blti-aes-key
          property: blti-aes-key
        - name: blti-aes-iv
          property: blti-aes-iv
    - name: test-rttlinfo.canvas.uw.edu-canvas-secrets
      externalKey: canvas/shared/secrets
      data:
        - name: canvas-api-token
          property: canvas-api-token
    - name: test-rttlinfo.canvas.uw.edu-ic-certs
      externalKey: rttl-info-lti/prod/ic-certs
      data:
        - name:rttlinfo.canvas.uw.edu-ic.cert
          property:rttlinfo.canvas.uw.edu-ic.cert
        - name:rttlinfo.canvas.uw.edu-ic.key
          property:rttlinfo.canvas.uw.edu-ic.key
environmentVariablesSecrets:
  django-secret:
    name: DJANGO_SECRET
    secretName: test-rttlinfo.canvas.uw.edu-secrets
    secretKey: django-secret
  LTIConsumers:
    name: LTI_CONSUMERS
    secretName: test-rttlinfo.canvas.uw.edu-shared-secrets
    secretKey: lti-consumers
  BLTIAESKey:
    name: BLTI_AES_KEY
    secretName: test-rttlinfo.canvas.uw.edu-shared-secrets
    secretKey: blti-aes-key
  BLTIAESIV:
    name: BLTI_AES_IV
    secretName: test-rttlinfo.canvas.uw.edu-shared-secrets
    secretKey: blti-aes-iv
  canvasAPIToken:
    name: CANVAS_OAUTH_BEARER
    secretName: test-rttlinfo.canvas.uw.edu-canvas-secrets
    secretKey: canvas-api-token
